%%{init: {'flowchart': {'curve': 'linear'}}}%%
flowchart LR

subgraph Driver Wiring
    direction TD
    classDef style2 fill:#2e3c50,stroke:#5b9bd5,color:#fff
    classDef style1 fill:#5c2525,stroke:#5b9bd5,color:#fff
    classDef style3 fill:#242b2b,stroke:#5b9bd5,color:#fff

    DM1[Slew 1]:::style3
    DM2[Slew 2]:::style3
    DM3[Boom]:::style3
    DM4[Jib Under]:::style3
    DM5[Jib Over]:::style3
    DM6[Hoist]:::style3
    DM7[Comp 1]:::style3
    DM8[Comp 2]:::style3

    LLS1[Shifter 1]:::style1
    LLS2[Shifter 2]:::style1
    LLS3[Shifter 3]:::style1
    LLS4[Shifter 4]:::style1

    GPX1:::style2
    GPX2:::style2
    GPX3:::style2
    GPX4:::style2
    GPX5:::style2
    GPX6:::style2
    GPX7:::style2
    GPX8:::style2
    GPX01:::style2
    GPX02:::style2
    GPX03:::style2
    GPX04:::style2
    GPX05:::style2
    GPX06:::style2
    GPX07:::style2
    GPX08:::style2

%%linkStyle 0,1 display:none
GPX2 ---|PUL 3.3V| LLS1 ---|PUL 5V| DM1
GPX4 ---|PUL 3.3V| LLS1 ---|PUL 5V| DM2

GPX6 ---|PUL 3.3V| LLS2 ---|PUL 5V| DM3
GPX8 ---|PUL 3.3V| LLS2 ---|PUL 5V| DM4

GPX02 ---|PUL 3.3V| LLS3 ---|PUL 5V| DM5
GPX04 ---|PUL 3.3V| LLS3 ---|PUL 5V| DM6

GPX06 ---|PUL 3.3V| LLS4 ---|PUL 5V| DM7
GPX08 ---|PUL 3.3V| LLS4 ---|PUL 5V| DM8


GPX1 ---|DIR 3.3V| LLS1 ---|DIR 5V| DM1
GPX3 ---|DIR 3.3V| LLS1 ---|DIR 5V| DM2

GPX5 ---|DIR 3.3V| LLS2 ---|DIR 5V| DM3
GPX7 ---|DIR 3.3V| LLS2 ---|DIR 5V| DM4

GPX01 ---|DIR 3.3V| LLS3 ---|DIR 5V| DM5
GPX03 ---|DIR 3.3V| LLS3 ---|DIR 5V| DM6

GPX05 ---|DIR 3.3V| LLS4 ---|DIR 5V| DM7
GPX07 ---|DIR 3.3V| LLS4 ---|DIR 5V| DM8
end

subgraph I2C Multiplexer Wiring
    GP1[GPX SDA]:::style2
    GP2[GPX SCL]:::style2

    MPXSD[SDA]:::style1
    MPXSC[SCL]:::style1
    SDA7:::style1
    SCL7:::style1
    SDA6:::style1
    SCL6:::style1
    SDA5:::style1
    SCL5:::style1
    SDA4:::style1
    SCL4:::style1
    SDA3:::style1
    SCL3:::style1

    ENC1[Jib Over]:::style3
    ENC2[Boom]:::style3
    ENC3[Jib Under]:::style3
    ENC4[Hoist]:::style3
    ENC5[Winch]:::style3

    X991[" "]
    style X991 display:none
    
GP1 --- MPXSD
GP2 --- MPXSC
SDA7 & SCL7 --- ENC1
SDA6 & SCL6 --- ENC2
SDA5 & SCL5 --- ENC3
SDA4 & SCL4 --- ENC4
SDA3 & SCL3 --- ENC5
MPXSD & MPXSC --- X991
SP1[CCM PICO]:::style2 --- SP2[MULTIPLEXER]:::style1 --- SP3[ENCODERS]:::style3
linkStyle 44,45,46,47 display:none




end

subgraph External Connections
URX0[UART RX]:::style1
UTX0[UART TX]:::style1
GN0[GND]:::style1
V0[3.3V]:::style1

URX1[UART RX]:::style2
UTX1[UART TX]:::style2
GN1[GND]:::style2
V1[3.3V]:::style2
MISO0[MISO]:::style2
MOSI0[MOSI]:::style2
SCK0[SCK]:::style2
CS0[CS]:::style2

X192[" "]
style X192 display:none

GN2[GND]:::style3
V2[3.3V]:::style3
MOSI1[MOSI]:::style3
MISO1[MISO]:::style3
SCK1[SCK]:::style3
CS1[CS]:::style3

FFG2["CCM PICO"]:::style2 --- FFG3[SPI ANTENNA]:::style3
URX0 --- URX1 --- X192
UTX0 --- UTX1 --- X192
FFG1["MRU PICO"]:::style1 --- FFG2
linkStyle 48,50,52,53 display:none
GN0 --- GN1 --- GN2
V0 --- V1 --- V2
MOSI0 --- MISO1
MISO0 --- MOSI1
CS0 --- CS1
SCK0 --- SCK1

end