%%{init: {'flowchart': {'curve': 'linear'}}}%%
flowchart TB

    classDef style2 fill:#2e3c50,stroke:#5b9bd5,color:#fff
    classDef style1 fill:#5c2525,stroke:#5b9bd5,color:#fff
    classDef style3 fill:#242b2b,stroke:#5b9bd5,color:#fff

subgraph Absolute I/O

    subgraph CCM
    USB["USB"]:::style1
    GP0:::style1
    GP1:::style1
    GP2:::style1
    GP3:::style1
    GP4:::style1
    GP5:::style1
    GP6:::style1
    GP7:::style1
    GP8:::style1
    GP9:::style1
    GP10:::style1
    GP11:::style1
    GP12:::style1
    GP13:::style1
    GP14:::style1
    GP15:::style1
    GP16:::style1
    GP17:::style1
    GP18:::style1
    GP19:::style1
    GP20:::style1
    GP21:::style1
    GP22:::style1
    GP26:::style1
    GP27:::style1
    GP28:::style1
    end

    subgraph INPUT
    USBI[USB]:::style3

    TX[UART TX]:::style3
    RX[UART RX]:::style3
    MISO:::style3
    MOSI:::style3
    SCK:::style3
    CS:::style3
    SDA[SDA]:::style3
    SCL[SCL]:::style3
    end

    subgraph OUTPUT
    TXU[UART TX]:::style2
    RXU[UART TX]:::style2

    MOSIU[MOSI]:::style2
    MISOU[MISO]:::style2
    SCKU[SCK]:::style2
    CSU[CS]:::style2

    SDAU[SDA]:::style2
    SCLU[SCL]:::style2

    JO[Jib Over]
    JU[Jib Under]
    S1[Slew 1]
    S2[Slew 2]
    Hoist
    C1[Comp 1]
    C2[Comp 2]
    Boom
    end


    CCM[CCM PICO]:::style1
    INPUT[Input]:::style3
    OUTPUT[Output]:::style2

    

    

 
    





USBI --- USB
TX --- GP4 --- TXU
RX --- GP5 --- RXU
GP0 --- |PUL| JU
GP1 --- |DIR| JU
GP3 --- |PUL| JO
GP2 --- |DIR| JO
GP8 --- |PUL| C1
GP20 --- |DIR| C1
GP11 --- |PUL| C2
GP10 --- |DIR| C2
GP13 --- |PUL| Hoist
GP12 --- |DIR| Hoist
GP15 --- |PUL| Boom
GP14 --- |DIR| Boom
GP6 --- |PUL| S1
GP7 --- |DIR| S1
GP22 --- |PUL| S2
GP21 --- |DIR| S2
SDA --- GP26 --- SDAU
SCL --- GP27 --- SCLU
SCK --- GP18 --- SCKU
MISO --- GP16 --- MOSIU
MOSI --- GP19 --- MISOU
CS --- GP17 --- CSU
end